=== nacho50900/sew/xml/circuito.dtd
<!ELEMENT circuito (nombre, longitud, anchura, fecha, hora, vueltas, localidad, pais, patrocinador, referencias, galeriaFotos, galeriaVideos, puntoOrigen, tramos, vencedor, clasificacion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ELEMENT anchura (#PCDATA)>
<!ATTLIST anchura unidad CDATA #REQUIRED>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT vueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>

<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT galeriaFotos (foto+)>
<!ELEMENT foto (#PCDATA)>

<!ELEMENT galeriaVideos (video+)>
<!ELEMENT video (#PCDATA)>

<!ELEMENT puntoOrigen (longitud, latitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud unidad CDATA #REQUIRED>
<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud unidad CDATA #REQUIRED>

<!ELEMENT tramos (tramo+)>
<!ELEMENT tramo (coordenadas, sector)>
<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT sector (#PCDATA)>
<!ATTLIST tramo distancia CDATA #REQUIRED>

<!ELEMENT vencedor (nombre, tiempo)>
<!ELEMENT tiempo (#PCDATA)>

<!ELEMENT clasificacion (piloto+)>
<!ELEMENT piloto (#PCDATA)>

=== nacho50900/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">

<circuito>
  <nombre>Petronas Sepang International Circuit</nombre>
  <longitud unidad="metros">5548</longitud>
  <anchura unidad="metros">15</anchura>
  <fecha>2025-09-24</fecha>
  <hora>15:00</hora>
  <vueltas>56</vueltas>
  <localidad>Sepang</localidad>
  <pais>Malasia</pais>
  <patrocinador>Petronas</patrocinador>

  <referencias>
    <referencia>https://www.formula1.com/en/racing/2025/Malaysia.html</referencia>
    <referencia>https://es.wikipedia.org/wiki/Circuito_Internacional_de_Sepang</referencia>
    <referencia>https://motorsport.com/malaysia-track-info</referencia>
  </referencias>

  <galeriaFotos>
    <foto>multimedia/Panorama.jpg</foto>
    <foto>multimedia/RectaMeta.jpg</foto>
    <foto>multimedia/PanoramaLateral.jpg</foto>
  </galeriaFotos>

  <galeriaVideos>
    <video>multimedia/POVOfOneLap.mp4</video>
    <video>multimedia/BirdEye.mp4</video>
  </galeriaVideos>

  <puntoOrigen>
    <longitud unidad="grados">101.44.16</longitud>
    <latitud unidad="grados">2.45.38</latitud>
    <altitud unidad="metros">35.79</altitud>
  </puntoOrigen>

  <tramos>
    <tramo distancia="595">
      <coordenadas>
        <longitud unidad="grados">101.7040</longitud>
        <latitud unidad="grados">2.45.37</latitud>
        <altitud unidad="metros">37.6</altitud>
      </coordenadas>
      <sector>0</sector>
    </tramo>
    <tramo distancia="150">
        <coordenadas>
          <longitud unidad="grados">101.43.59</longitud>
          <latitud unidad="grados">2.45.39</latitud>
          <altitud unidad="metros">36.3</altitud>
        </coordenadas>
        <sector>0</sector>
    </tramo>
    <tramo distancia="142">
        <coordenadas>
          <longitud unidad="grados">101.43.59</longitud>
          <latitud unidad="grados">2.45.41</latitud>
          <altitud unidad="metros">31.18</altitud>
        </coordenadas>
        <sector>0</sector>
    </tramo>
    <tramo distancia="300">
      <coordenadas>
        <longitud unidad="grados">101.44.02</longitud>
        <latitud unidad="grados">2.45.49</latitud>
        <altitud unidad="metros">22.52</altitud>
      </coordenadas>
      <sector>0</sector>
    </tramo>
    <tramo distancia="395">
        <coordenadas>
          <longitud unidad="grados">101.44.14</longitud>
          <latitud unidad="grados">2.45.54</latitud>
          <altitud unidad="metros">35.85</altitud>
        </coordenadas>
        <sector>1</sector>
    </tramo>
    <tramo distancia="40">
        <coordenadas>
          <longitud unidad="grados">101.44.15</longitud>
          <latitud unidad="grados">2.45.53</latitud>
          <altitud unidad="metros">37.83</altitud>
        </coordenadas>
        <sector>1</sector>
    </tramo>
    <tramo distancia="200">
      <coordenadas>
        <longitud unidad="grados">101.44.16</longitud>
        <latitud unidad="grados">2.45.17</latitud>
        <altitud unidad="metros">40.05</altitud>
      </coordenadas>
      <sector>1</sector>
    </tramo>
    <tramo distancia="285">
        <coordenadas>
          <longitud unidad="grados">101.44.23</longitud>
          <latitud unidad="grados">2.45.45</latitud>
          <altitud unidad="metros">37.09</altitud>
        </coordenadas>
        <sector>8</sector>
    </tramo>
    <tramo distancia="175">
      <coordenadas>
        <longitud unidad="grados">101.44.28</longitud>
        <latitud unidad="grados">2.45.45</latitud>
        <altitud unidad="metros">38.65</altitud>
      </coordenadas>
      <sector>1</sector>
    </tramo>
    <tramo distancia="290">
      <coordenadas>
        <longitud unidad="grados">101.44.34</longitud>
        <latitud unidad="grados">2.45.38</latitud>
        <altitud unidad="metros">38.88</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="30">
      <coordenadas>
        <longitud unidad="grados">101.44.34</longitud>
        <latitud unidad="grados">2.45.37</latitud>
        <altitud unidad="metros">38.72</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="75">
      <coordenadas>
        <longitud unidad="grados">101.44.34</longitud>
        <latitud unidad="grados">2.45.35</latitud>
        <altitud unidad="metros">38.03</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
      <tramo distancia="40">
      <coordenadas>
        <longitud unidad="grados">101.44.32</longitud>
        <latitud unidad="grados">2.45.34</latitud>
        <altitud unidad="metros">37.67</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="435">
      <coordenadas>
        <longitud unidad="grados">101.44.18</longitud>
        <latitud unidad="grados">2.45.33</latitud>
        <altitud unidad="metros">33.59</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="435">
      <coordenadas>
        <longitud unidad="grados">101.44.18</longitud>
        <latitud unidad="grados">2.45.33</latitud>
        <altitud unidad="metros">33.59</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="50">
      <coordenadas>
        <longitud unidad="grados">101.44.18</longitud>
        <latitud unidad="grados">2.45.32</latitud>
        <altitud unidad="metros">35.16</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="65">
      <coordenadas>
        <longitud unidad="grados">101.44.20</longitud>
        <latitud unidad="grados">2.45.31</latitud>
        <altitud unidad="metros">38.94</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="65">
      <coordenadas>
        <longitud unidad="grados">101.44.21</longitud>
        <latitud unidad="grados">2.45.29</latitud>
        <altitud unidad="metros">41.49</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="180">
      <coordenadas>
        <longitud unidad="grados">101.44.19</longitud>
        <latitud unidad="grados">2.45.24</latitud>
        <altitud unidad="metros">44.36</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="60">
      <coordenadas>
        <longitud unidad="grados">101.44.18</longitud>
        <latitud unidad="grados">2.45.24</latitud>
        <altitud unidad="metros">43.71</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="265">
      <coordenadas>
        <longitud unidad="grados">101.44.11</longitud>
        <latitud unidad="grados">2.45.29</latitud>
        <altitud unidad="metros">37.54</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="80">
      <coordenadas>
        <longitud unidad="grados">101.44.09</longitud>
        <latitud unidad="grados">2.45.29</latitud>
        <altitud unidad="metros">35.2</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="65">
      <coordenadas>
        <longitud unidad="grados">101.44.07</longitud>
        <latitud unidad="grados">2.45.28</latitud>
        <altitud unidad="metros">33.6</altitud>
      </coordenadas>
      <sector>2</sector>
    </tramo>
    <tramo distancia="230">
      <coordenadas>
        <longitud unidad="grados">101.44.01</longitud>
        <latitud unidad="grados">2.45.30</latitud>
        <altitud unidad="metros">35.13</altitud>
      </coordenadas>
      <sector>3</sector>
    </tramo>
    <tramo distancia="65">
      <coordenadas>
        <longitud unidad="grados">101.44.01</longitud>
        <latitud unidad="grados">2.45.32</latitud>
        <altitud unidad="metros">36.53</altitud>
      </coordenadas>
      <sector>3</sector>
    </tramo>
    <tramo distancia="830">
      <coordenadas>
        <longitud unidad="grados">101.44.28</longitud>
        <latitud unidad="grados">2.45.37</latitud>
        <altitud unidad="metros">36.32</altitud>
      </coordenadas>
      <sector>3</sector>
    </tramo>
    <tramo distancia="130">
      <coordenadas>
        <longitud unidad="grados">101.44.28</longitud>
        <latitud unidad="grados">2.45.39</latitud>
        <altitud unidad="metros">36.74</altitud>
      </coordenadas>
      <sector>3</sector>
    </tramo>
    <tramo distancia="310">
      <coordenadas>
        <longitud unidad="grados">101.44.18</longitud>
        <latitud unidad="grados">2.45.38</latitud>
        <altitud unidad="metros">35.76</altitud>
      </coordenadas>
      <sector>3</sector>
    </tramo>
  </tramos>

  <vencedor>
    <nombre>Álex Márquez</nombre>
    <tiempo>00:40:09</tiempo>
  </vencedor>

  <clasificacion>
    <piloto>Marc Márquez</piloto>
    <piloto>Álex Márquez</piloto>
    <piloto>Marco Bezzecchi</piloto>
  </clasificacion>

</circuito>
